name             "opsview"
maintainer       "NREL"
maintainer_email "nick.muerdter@nrel.gov"
license          "All rights reserved"
description      "Installs/Configures opsview"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.1.1"

depends "acl"
depends "apache2"
depends "database"
depends "mysql"
depends "openssl"
depends "perl"
depends "php"
depends "python"
depends "rbenv"
depends "sudo"
depends "yum"
depends "yum-epel"
